### ISSUE TITLE
ability to list entities

### ISSUE THREAD

**Issue by jeromekleinen** [M-u-S/TA-debug-refresh#2]
Hi,

It would be cool if you could specify a command line parameter to | refresh which would just list the available entities that can be refreshed, without actually reloading them. Alternatively/additionally some common defaults could be useful (f.e. reloading props.conf, transforms.conf etc).

Jerome

**Comment by M-u-S** [comment]
Hello @jeromekleinen 

Thanks for your feedback. This has been added to the latest version which I will upload shortly.
